// api status code
export const statusCode = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

// should remove this later on
export const BZ_STATUS_CODE = {
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  RECORD_ALREADY_EXIST: "RECORD_ALREADY_EXIST",
  UNAUTHORIZED: "UNAUTHORIZED",
  ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
};

export enum ERROR_CODE {
  RECORD_NOT_FOUND = "RECORD_NOT_FOUND",
  RECORD_ALREADY_EXIST = "RECORD_ALREADY_EXIST",
  UNAUTHORIZED = "UNAUTHORIZED",
  ACCOUNT_NOT_VERIFIED = "ACCOUNT_NOT_VERIFIED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  CONTRACT_NOT_CANCELLED = "CONTRACT_NOT_CANCELLED",
  CONTRACT_ACTIVE = "CONTRACT_ACTIVE",
  CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND",
}
